services:
    app.bank_repository:
        class: App\Repository\BankRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Bank'
    app.parent_repository:
        class: App\Repository\PersonRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Person'
    app.pre_register_repository:
        class: App\Repository\PreRegisterRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:PreRegister'
    app.city_repository:
        class: App\Repository\CityRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:City'
    app.province_repository:
        class: App\Repository\ProvinceRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Province'
    app.teacher_repository:
        class: App\Repository\TeacherRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Teacher'
    app.teacher_absence_repository:
        class: App\Repository\TeacherAbsenceRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:TeacherAbsence'
    app.student_repository:
        class: App\Repository\StudentRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Student'
    app.student_absence_repository:
        class: App\Repository\StudentAbsenceRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:StudentAbsence'
    app.event_repository:
        class: App\Repository\EventRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Event'
    app.class_group_repository:
        class: App\Repository\ClassGroupRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:ClassGroup'
    app.tariff_repository:
        class: App\Repository\TariffRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Tariff'
    app.receipt_repository:
        class: App\Repository\ReceiptRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Receipt'
    app.invoice_repository:
        class: App\Repository\InvoiceRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Invoice'
    app.provider_repository:
        class: App\Repository\ProviderRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Provider'
    app.spending_category_repository:
        class: App\Repository\SpendingCategoryRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:SpendingCategory'
    app.spending_repository:
        class: App\Repository\SpendingRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:Spending'
    app.contact_message_repository:
        class: App\Repository\ContactMessageRepository
        public: true
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'App:ContactMessage'
