doctrine_migrations:
    enable_profiler: '%kernel.debug%'
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name:              'migration_versions'
            version_column_name:     'version'
            executed_at_column_name: 'executed_at'
            version_column_length:   191
