hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [facebook]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%env(FACEBOOK_API_KEY)%'
            client_secret:       '%env(FACEBOOK_API_SECRET)%'
            scope:               "email"
            options:
                display: popup
                csrf: true
