sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user:  App\Entity\User
        group: App\Entity\Group
    admin:
        user:
            class:       App\Admin\UserAdmin
            controller:  App\Controller\Admin\UserAdminController
            translation: messages
        group:
            class:       Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:  SonataAdminBundle:CRUD
            translation: messages
