stof_doctrine_extensions:
    default_locale: '%env(resolve:DEFAULT_LOCALE)%'
    orm:
        default:
            timestampable:  true
            sluggable:      true
            softdeleteable: false
            translatable:   false
            sortable:       false
            tree:           false
