vich_uploader:
    db_driver: orm
    mappings:
        teacher:
            uri_prefix:         '/uploads/images/teacher'
            upload_destination: '%kernel.project_dir%/public/uploads/images/teacher'
            namer:              'vich_uploader.namer_uniqid'
        service:
            uri_prefix:         '/uploads/images/service'
            upload_destination: '%kernel.project_dir%/public/uploads/images/service'
            namer:              'vich_uploader.namer_uniqid'
        spending:
            uri_prefix:         '/uploads/documents/spending'
            upload_destination: '%kernel.project_dir%/public/uploads/documents/spending'
            namer:              'vich_uploader.namer_uniqid'
