vich_uploader:
    db_driver: orm
    mappings:
        post:
            uri_prefix: '/uploads/images/post'
            upload_destination: '%kernel.project_dir%/public/uploads/images/post'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        teacher:
            uri_prefix: '/uploads/images/teacher'
            upload_destination: '%kernel.project_dir%/public/uploads/images/teacher'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        service:
            uri_prefix: '/uploads/images/service'
            upload_destination: '%kernel.project_dir%/public/uploads/images/service'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
        spending:
            uri_prefix: '/uploads/documents/spending'
            upload_destination: '%kernel.project_dir%/public/uploads/documents/spending'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
