monolog:
    handlers:
        main:
            path:     '%kernel.logs_dir%/%kernel.environment%.log'
            type:     stream
            level:    debug
            channels: [ '!event' ]
        console:
            type:                   console
            process_psr_3_messages: false
            channels:               [ '!event', '!doctrine', '!console' ]
